### ISSUE TITLE
Observation Date

### ISSUE THREAD

**Issue by Sciss** [jankotek/asterope-scala-legacy#1]
I have a perhaps stupid question—is it possible to specify the date at which the stars are observed? I.e., can I paint a chart for 01.01.2013, 02.01.2013, ... 22.07.2013? Or are the data fixed for a specific date? If so, where would I do that (in the API)? Thanks!

**Comment by jankotek** [comment]
No, this code does not support time&location. It was never finished.

**Comment by Sciss** [comment]
Ok, that's a pity. Is that what the ephem package is supposed to do? Do you happen to know any JVM based library that do such thing? Thanks again!

**Comment by jankotek** [comment]
Dont use this project.
Checkout JParsec

On Monday 22 July 2013 09:43:05 Sciss wrote:

Ok, that's a pity. Is that what the ephem package is supposed to do? Do you 
happen to know any JVM based library that do such thing? Thanks again! 
—
Reply to this email directly or view it on GitHub.

## 

Jan Kotek

Hope this helps.
